export { default as Dashboard } from "./Dashboard";
export { default as Mint } from "./Mint";
export { default as Gallery } from "./Gallery";
export { default as Find } from "./Find";
export { default as Swap } from "./Swap";
export { default as Chart } from "./Chart";
export { default as ToS } from "./ToS";
export { default as Policy } from "./Policy";
export { default as NotFound } from "./404";
